### ISSUE TITLE
BUG: compatibility issue with TFP 0.7.0

### ISSUE THREAD

**Issue by rcabanasdepaz** [PGM-Lab/InferPy#168]
InferPy does not work with TFP 0.7.0 because the ``rv_all`` list has been removed. For example, when importing InferPy:

```
import inferpy as in 
```

I get 

```
  File "[...]/InferPy/inferpy/models/random_variable.py", line 32, in <module>
    distributions_all = generated_random_variables.rv_all
AttributeError: module 'tensorflow_probability.python.edward2.generated_random_variables' has no attribute 'rv_all'

```
The packages installed are:

tensorflow==1.14.0
tensorflow-estimator==1.14.0
tensorflow-probability==0.7.0

**Comment by jcozar87** [comment]
Closed in 26c03b71729d92103f7f77a6dc7c6c3bb67a43f3
